image: node:18.12.1-alpine

stages:
  - test
  - build

.setup:
  before_script:
    - npm ci --cache .npm --prefer-offline
    - cp videos.example.json videos.json
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

shellcheck:
  image: koalaman/shellcheck-alpine:latest
  stage: test
  script:
    - shellcheck scripts/*.sh

lint_js:
  stage: test
  extends:
    - .setup
  script:
    - npm run lint

run_build:
  stage: build
  extends:
    - .setup
  script:
    - npm run build